# Datenstrom Yellow extension settings

Extension: Check
Version: 1.0.1
Description: Find broken links.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-check/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-check
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:06:45
Status: maintained
system/workers/check.php: check.php, create, update
